"""empty message

Revision ID: 05c6e96b3663
Revises: 
Create Date: 2020-11-05 09:07:25.361764

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "05c6e96b3663"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "sensor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("notify_active", sa.Boolean(), nullable=True),
        sa.Column("max_temp", sa.Integer(), nullable=True),
        sa.Column("min_temp", sa.Integer(), nullable=True),
        sa.Column("max_humidity", sa.Integer(), nullable=True),
        sa.Column("min_humidity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sensor_name"), "sensor", ["name"], unique=False)
    op.create_index(
        op.f("ix_sensor_notify_active"), "sensor", ["notify_active"], unique=False
    )
    op.create_index(op.f("ix_sensor_uuid"), "sensor", ["uuid"], unique=True)
    op.create_table(
        "reading",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["sensor_id"], ["sensor.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reading_key"), "reading", ["key"], unique=False)
    op.create_index(
        op.f("ix_reading_timestamp"), "reading", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reading_timestamp"), table_name="reading")
    op.drop_index(op.f("ix_reading_key"), table_name="reading")
    op.drop_table("reading")
    op.drop_index(op.f("ix_sensor_uuid"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_notify_active"), table_name="sensor")
    op.drop_index(op.f("ix_sensor_name"), table_name="sensor")
    op.drop_table("sensor")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
