"""empty message

Revision ID: de026b37e590
Revises: 05c6e96b3663
Create Date: 2020-11-05 23:13:39.833693

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "de026b37e590"
down_revision = "05c6e96b3663"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sensor", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sensor", "last_seen")
    # ### end Alembic commands ###
